---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: repo-src
  - name: dependency-cache

run:
  path: repo-src/ci/scripts/run_tests.sh
