apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-nodejs
  namespace: test-nodejs
  name: test-nodejs
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-nodejs
      annotations:
        kubernetes.io/change-cause: "FIXME"
    spec:
      containers:
      - name: test-nodejs
        image: harbor.pcfgcp.pkhamdee.com/library/test-nodejs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
