---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: test-nodejs
    type: git
    source: &repo-source
      uri: https://github.com/pkhamdee/test-nodejs
      branch: master

  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

  - name: harbor-image
    type: docker-image
    source:
      username: {{harbor_username}}
      password: {{harbor_password}}
      repository: {{harbor_repository}}
      insecure_registries:
        - {{harbor_insecure_registry}}       

jobs:
  - name: Install dependencies
    plan:
      - get: test-nodejs
        trigger: true
      - get: dependency-cache

  - name: Run Tests
    plan:
      - get: test-nodejs
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]

      - task: run the test suite
        file: test-nodejs/ci/tasks/run_tests.yml     

  - name: Build docker image
    plan:
      - get: test-nodejs
        trigger: true
        passed: [Run Tests]
      - put: harbor-image
        params:
          build: test-nodejs      
