---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "latest"    

resources:
  - name: test-nodejs
    type: git
    source: &repo-source
      uri: https://github.com/pkhamdee/test-nodejs
      branch: master

  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

  - name: k8s-develop
    type: kubernetes
    source:
      kubeconfig: {{kubeconfig-develop}} 

  - name: harbor-image
    type: docker-image
    source:
      username: {{harbor_username}}
      password: {{harbor_password}}
      repository: {{harbor_repository}}
      insecure_registries:
        - {{harbor_insecure_registry}}
      ca_certs:
        - domain: harbor.pcfgcp.pkhamdee.com:443
          cert: {{harbor_cert}}           

docker-params: &docker-params
  tag: test-nodejs/.git/HEAD
  tag_as_latest: true
  cache: true
  cache_tag: latest

jobs:
  - name: Install dependencies
    plan:
      - get: test-nodejs
        trigger: true
      - get: dependency-cache

  - name: Run Tests
    plan:
      - get: test-nodejs
        trigger: true
        passed: [Install dependencies]
      - get: dependency-cache
        passed: [Install dependencies]

      - task: run the test suite
        file: test-nodejs/ci/tasks/run_tests.yml     

  - name: Build docker image
    plan:
      - get: test-nodejs
        trigger: true
        passed: [Run Tests] 
      - put: harbor-image
        params:
          <<: *docker-params
          build: test-nodejs

  - name: Deploy to Develop
    plan:
      - get: harbor-image
        trigger: true
        passed: [Build docker image]
      - get: test-nodejs
        passed: [Build docker image]  

      - task: update-k8s-manifest
        params:
          <<: *docker-params
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
          - name: test-nodejs
          - name: harbor-image
          outputs:
          - name: updated
          run:
            path: bash
            args:
            - -c
            - |
              set -e
              sed "s/:latest/@${tag}/g" test-nodejs/k8s/test-nodejs.yml | \
              sed "s/FIXME/Bump to ${tag}/g" | \
              sed "s/namespace: test-nodejs/namespace: test-nodejs-dev/g" > updated/test-nodejs.yml  

      - put: k8s-develop
        params:
          kubectl: apply -f updated/test-nodejs.yml
          wait_until_ready: 120
          wait_until_ready_selector: app=test-nodejs    

